.

diff --git a/application/app/Jenkinsfile b/application/app/Jenkinsfile
--- a/application/app/Jenkinsfile
+++ b/application/app/Jenkinsfile
@@ -48,17 +48,20 @@ pipeline {
         stage('Merge Feature Branch into Main and Push') {
             steps {
                 script {
-                    
                     sh """
                     git config --global --add safe.directory /home/jenkins/agent/workspace/weather-app
                     git config --global user.email "halias32236@gmail.com"
                     git config --global user.name "Talh12"
                     git fetch origin '+refs/heads/*:refs/remotes/origin/*'
                     git checkout ${MAIN_BRANCH}
-                    git merge origin/${FEATURE_BRANCH}
-                    git add -A
-                    git commit -m "Merge ${FEATURE_BRANCH} into ${MAIN_BRANCH} by Jenkins"
-                    git push origin ${MAIN_BRANCH}
+                    git merge origin/${FEATURE_BRANCH} || { echo "Merge failed"; exit 1; }
+                    if [ -n "$(git status --porcelain)" ]; then
+                        git add -A
+                        git commit -m "Merge ${FEATURE_BRANCH} into ${MAIN_BRANCH} by Jenkins"
+                        git push origin ${MAIN_BRANCH}
+                    else
+                        echo "No changes to commit"
+                    fi
                     """
                 }
             }
